### ISSUE TITLE
PHP Exploit Warning

### ISSUE THREAD

**Issue by superflausch** [tinify/tinify-php#33]
Our hosting provider scans their servers for known exploits from time to time. warned us about a know exploit and blocked access to the following file within minify-php:

`test/integration.php`

The reason given is

`# Known exploit = [Fingerprint Match (fp)] [PHP RFI Exploit [P2060]]`

Did anyone else noticed this as well? Anything we can do? Or can this be updated/fixed in the lib?

Cheers.

**Comment by rkoopmans** [comment]
Hi Superflausch,

That sounds bad. Since the tinify PHP package is produced  from this repository, the code should be visible [here](https://github.com/tinify/tinify-php/blob/master/test/integration.php).

It is probably a false positive, do you have any more information on the software that reports the 'exploit'? We would like to have some more information on what detects it, and why.

Could you also send the test/integration.php file that got reported by your hosting provider to support@tinify.com?

**Comment by rkoopmans** [comment]
Closing this issue because we haven't heard anything back. There is nothing we can do at this time.

Feel free to reopen.
